/**
 * Pre-flight: confirm all files the browser needs are present in docs/.
 *
 * The team-slug list is dynamic (generated by fetch-fixtures.mjs into
 * docs/config.js as window.NSM_SUNDAY_CONFIG.TEAM_SLUGS) so this script reads
 * the generated config and asserts a .ics exists for every slug.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DOCS = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'docs');

// Bootstrap base — required regardless of how many teams the season has.
const baseRequired = [
  'fixtures.json',
  'config.js',
  'render.mjs',
  'index.html',
  'venues.html',
  'manifest.webmanifest',
  'sw.js',
  'assets/icon-192.png',
  'assets/icon-512.png',
  'assets/icon-512-maskable.png',
  'assets/apple-touch-icon-180.png',
];

let missing = 0;
const fail = (rel) => { console.error(`MISSING: docs/${rel}`); missing++; };

for (const f of baseRequired) {
  if (!fs.existsSync(path.join(DOCS, f))) fail(f);
}

// Dynamic ICS check — pull TEAM_SLUGS from the generated config.js. The file
// is a tiny `window.NSM_SUNDAY_CONFIG = {...};` assignment; we don't need a
// real browser, just to eval it.
const cfgPath = path.join(DOCS, 'config.js');
if (fs.existsSync(cfgPath)) {
  const stub = { NSM_SUNDAY_CONFIG: null };
  const src = fs.readFileSync(cfgPath, 'utf8');
  try {
    const fn = new Function('window', src + ';return window.NSM_SUNDAY_CONFIG;');
    const cfg = fn(stub);
    const slugs = Object.keys(cfg?.TEAM_SLUGS || {});
    if (slugs.length === 0) {
      console.warn('check: TEAM_SLUGS empty in docs/config.js — first CI run hasn\'t happened yet?');
    }
    for (const slug of slugs) {
      if (!fs.existsSync(path.join(DOCS, `${slug}.ics`))) fail(`${slug}.ics`);
    }
  } catch (err) {
    console.error(`check: could not parse docs/config.js — ${err.message}`);
    missing++;
  }
}

if (missing > 0) {
  console.error(`\n${missing} required file(s) missing from docs/. Run: node scripts/fetch-fixtures.mjs`);
  process.exit(1);
} else {
  console.log('check: all required files present.');
}
